---
- hosts: local
  become: true
  roles:
    - role: geerlingguy.repo-epel
    - role: andrewrothstein.wget
    - role: mdklatt.python3
    - role: geerlingguy.ansible
    - role: geerlingguy.git
    - role: uchida.miniconda
    - role: geerlingguy.pip
    - role: geerlingguy.nfs

