- src: geerlingguy.repo-epel
  version: 1.2.4
- src: geerlingguy.ansible
  version: 2.0.2
- src: mdklatt.python3
  version: v0.3.0
- src: andrewrothstein.wget
  version: v1.0.0
- src: geerlingguy.git
  version: 2.1.0
- src: geerlingguy.nfs
  version: 1.5.0
- src: geerlingguy.pip
  version: 1.3.0
- src: uchida.miniconda
  version: 0.3.0
- src: manala.vim
  version: 2.0.1
- src: nickjj.sshd
  version: v0.3.0
