- src: galaxyproject.galaxy
  version: 0.9.5
- src: galaxyproject.nginx
  version: 0.6.4
- src: galaxyproject.postgresql
  version: 1.0.2
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 1.3.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.galaxy_systemd
  version: 0.1.2
- src: usegalaxy_eu.certbot
  version: 0.1.3
- src: https://github.com/usegalaxy-eu/ansible-role-supervisor
  name: usegalaxy-eu.supervisor
- src: https://github.com/usegalaxy-eu/ansible-certbot
  name: usegalaxy-eu.certbot
- src: galaxyproject.repos
  version: 0.0.1
- src: galaxyproject.slurm
  version: 0.1.2
- src: usegalaxy_eu.gxadmin
  version: 0.0.2
